"""Framework-specific detection rules.

Covers LangChain, AutoGen, CrewAI, and Dify patterns that
introduce security risk beyond what the generic PI/TA/DL rules catch.
"""

from ..engine import RegexRule
from ..findings import Severity

# Shared regex fragments for multiline patterns — stop at function/class boundaries
_STOP_AT_FUNC = r"(?:(?!\n\s*(?:def\s|class\s|@)).)"
_STOP_AT_DECORATOR = r"(?:(?!\n\s*(?:@|def\s|class\s)).)"


class LangChainToolNoConfirmRule(RegexRule):
    """Detect LangChain @tool functions that execute dangerous operations
    without user confirmation or sandboxing.

    LangChain tools decorated with @tool can invoke shell commands, file
    I/O, and network calls. Without an explicit confirmation step
    (input("Are you sure?") or a confirmation callback), an attacker
    who controls the LLM prompt can trigger arbitrary tool execution.
    """

    rule_id = "FW-001"
    title = "LangChain @tool executes high-risk operation without confirmation"
    description = (
        "LangChain @tool function wraps a dangerous operation (shell command, "
        "file delete, HTTP request) without requiring user confirmation. "
        "An attacker who injects into the LLM prompt can trigger this tool."
    )

    file_patterns = ["*.py"]

    patterns = [
        # @tool decorator followed by function containing dangerous calls
        (r"@tool", "@tool decorator without confirmation guard"),
        # subprocess/os.system inside tool without confirmation
        (
            rf"def\s+\w+[^\n]*\n{_STOP_AT_FUNC}{{0,500}}?(?:subprocess\.|os\.system|os\.popen)",
            "Shell execution inside @tool function — missing confirmation prompt",
        ),
        # File delete/write inside tool without confirmation
        (
            rf"def\s+\w+[^\n]*\n{_STOP_AT_FUNC}{{0,500}}?(?:os\.remove|shutil\.rmtree|Path\(.*\)\.unlink)",
            "File deletion inside @tool function — missing confirmation prompt",
        ),
        # requests.post without user approval check
        (
            rf"def\s+\w+[^\n]*\n{_STOP_AT_FUNC}{{0,500}}?requests\.(?:post|put|delete|patch)",
            "Outbound HTTP inside @tool function — missing confirmation prompt",
        ),
    ]

    owasp_ids = ["LLM06", "AG-02"]

    def _severity(self):
        return Severity.HIGH

    def fix_suggestion(self) -> str:
        return (
            "Add a confirmation callback to the @tool decorator:\n"
            "  @tool(confirm=True)  # LangChain will prompt user before execution\n"
            "Or add an explicit guard inside the function:\n"
            "  if not input('Confirm (y/n)? ').lower().startswith('y'): return"
        )


class AutoGenCodeExecRule(RegexRule):
    """Detect AutoGen agent configurations that enable code execution
    without Docker sandboxing.

    AutoGen's ConversableAgent can execute Python code generated by the LLM.
    Without use_docker=True, this code runs directly on the host.
    """

    rule_id = "FW-002"
    title = "AutoGen agent enables code execution without Docker sandbox"
    description = (
        "AutoGen agent configured with code_execution_config that does not "
        "specify use_docker=True. LLM-generated code will execute directly "
        "on the host machine, allowing arbitrary command execution."
    )

    file_patterns = ["*.py"]

    patterns = [
        # code_execution_config without use_docker
        (
            r'code_execution_config\s*=\s*\{[^}]*\}',
            "AutoGen code_execution_config dict — verify use_docker is True",
        ),
        # ConversableAgent or AssistantAgent without docker
        (
            r'(?:ConversableAgent|AssistantAgent)\s*\([^)]*code_execution',
            "AutoGen agent with code execution — verify Docker sandboxing",
        ),
        # Explicit use_docker=False
        (
            r"use_docker\s*=\s*False",
            "AutoGen: Docker sandbox explicitly disabled — host exposed to LLM code",
        ),
    ]

    owasp_ids = ["LLM06", "AG-10"]

    def _severity(self):
        return Severity.CRITICAL

    def fix_suggestion(self) -> str:
        return (
            "Always use Docker sandboxing for AutoGen code execution:\n"
            '  code_execution_config={"work_dir": "coding", "use_docker": True}\n'
            "If Docker is unavailable, disable code execution entirely:\n"
            "  code_execution_config=False"
        )


class CrewAITaskExecRule(RegexRule):
    """Detect CrewAI Task definitions that enable arbitrary code execution
    or shell access without validation of the tool output.
    """

    rule_id = "FW-003"
    title = "CrewAI Task enables code execution without output validation"
    description = (
        "CrewAI Task with allow_code_execution=True or a shell-access tool "
        "without validating the LLM-generated code before execution. The LLM "
        "may generate destructive commands under prompt injection."
    )

    file_patterns = ["*.py"]

    patterns = [
        # allow_code_execution=True without validation tool
        (
            r"allow_code_execution\s*=\s*True",
            "CrewAI Task allows code execution — add output validation before exec",
        ),
        # Tool that wraps os.system / subprocess
        (
            rf"class\s+\w*Tool\w*[^\n]*\n{_STOP_AT_FUNC}{{0,500}}?(?:os\.system|subprocess\.)",
            "CrewAI Tool with shell access — output not validated before execution",
        ),
    ]

    owasp_ids = ["LLM06", "AG-02"]

    def _severity(self):
        return Severity.HIGH

    def fix_suggestion(self) -> str:
        return (
            "Add a validation layer that reviews LLM-generated code before execution:\n"
            "  1. Parse the generated code with ast.parse()\n"
            "  2. Walk the AST and reject dangerous nodes (os.system, __import__, eval)\n"
            "  3. Run in a restricted subprocess with timeout and filesystem isolation"
        )


class DifyAPIPluginNoAuthRule(RegexRule):
    """Detect Dify plugin API endpoints that lack authentication checks.

    Dify plugins expose API routes that can be called by any authenticated
    Dify user. Plugin authors often forget that these routes need explicit
    permission validation — the Dify platform does not enforce it automatically.
    """

    rule_id = "FW-004"
    title = "Dify plugin API endpoint missing permission check"
    description = (
        "Dify plugin defines an API route without verifying the caller's "
        "workspace permissions. Any authenticated user in the Dify instance "
        "can invoke this endpoint, potentially accessing other users' data."
    )

    file_patterns = ["*.py"]

    patterns = [
        # Dify plugin route decorator without permission check
        (
            rf"@app\.route[^\n]*\n{_STOP_AT_DECORATOR}{{0,500}}?def\s+\w+[^\n]*\n{_STOP_AT_FUNC}{{0,500}}?(?!.*?(?:permission|auth|workspace_id|current_user))",
            "Dify plugin route — verify workspace-level permission is checked",
        ),
    ]

    owasp_ids = ["AG-03"]

    def _severity(self):
        return Severity.MEDIUM

    def fix_suggestion(self) -> str:
        return (
            "Add workspace permission check to the endpoint:\n"
            "  from dify_plugin import require_workspace_permission\n"
            "  @app.route('/my-endpoint')\n"
            "  @require_workspace_permission\n"
            "  def handler(): ..."
        )
